---
- name: Add node
  bigip_node:
      server: "{{ inventory_hostname }}"
#      user: "{{ username }}"
#      password: "{{ F5_PASSWORD }}"
      state: "present"
      partition: "Common"
      host: "{{ host_ip }}"
      name: "{{ member_name }}"
      monitors:
        - /Common/icmp
